# Generated by Django 5.0.6 on 2024-05-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=15)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
